theme: jekyll-theme-minimal
title: Alfred Kirsch
description: <h3><a href="https://alfred-kirsch.github.io/research">Research</a> | Talks </h3><h3><a href="https://alfred-kirsch.github.io/teaching">Teaching & Students</a></h3> PhD student in Mathematics,<br> <a href="https://cermics-lab.enpc.fr/">CERMICS</a> (Ã‰cole des Ponts) &<br><a href="https://team.inria.fr/matherials/">Inria Matherials</a> (Paris),<br>&#x1F4E7; alfred.kirsch at enpc.fr
github:
    is_user_page: false
    is_project_page: false
