theme: jekyll-theme-minimal
title: Alfred Kirsch
description: PhD student in Mathematics at CERMICS, Ã‰cole des Ponts, alfred.kirsch at enpc.fr, <a href="https://alfred-kirsch.github.io">Home</a> | <a href="https://alfred-kirsch.github.io/research">Research</a> | <a href="https://alfred-kirsch.github.io/teaching">Teaching</a>
is_project_page: false
is_user_page: false
