theme: jekyll-theme-minimal
title: Alfred Kirsch
description: PhD student in Mathematics,<br> <a href="https://cermics-lab.enpc.fr/">CERMICS</a> (Ã‰cole des Ponts) &<br><a href="https://team.inria.fr/matherials/">Inria Matherials</a> (Paris),<br>alfred.kirsch at enpc.fr,<br><h2><a href="https://alfred-kirsch.github.io">Home</a> | <a href="https://alfred-kirsch.github.io/research">Research</a> | <a href="https://alfred-kirsch.github.io/teaching">Teaching</a></h2>
github:
    is_user_page: false
    is_project_page: false
