theme: jekyll-theme-minimal
title: Alfred Kirsch
description: PhD student in Mathematics at CERMICS, Ã‰cole des Ponts, alfred.kirsch at enpc.fr, <a href="https://alfred-kirsch.github.io/research">Research</a>
