theme: jekyll-theme-minimal
title: Alfred Kirsch
description: PhD student in Mathematics,<br>CERMICS - Ã‰cole des Ponts and Inria Paris,<br>alfred.kirsch at enpc.fr,<br><a href="https://alfred-kirsch.github.io">Home</a> | <a href="https://alfred-kirsch.github.io/research">Research</a> | <a href="https://alfred-kirsch.github.io/teaching">Teaching</a>
github:
    is_user_page: false
    is_project_page: false
